title: "Vera"
description: "用 AI，陪伴成長"
url: "https://vera-with-ai.github.io"
baseurl: ""
lang: zh-TW

collections:
  tools:
    output: true
    permalink: /ai-tools/:name/

markdown: kramdown

css_version: 14

exclude:
  - _templates
  - README.md
